apiVersion: apps/v1
kind: Deployment
metadata:
  name: mydeployment
  labels:
    env: dev
spec:
  replicas: 4
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  selector:
    matchLabels:
      app: webs
      env: dev
  template:
    metadata:
      labels:
        app: webs
        env: dev
    spec:
      containers:
        - name: pyapp
          image: debian:12-slim
          ports:
          - containerPort: 80
