apiVersion: v1
kind: Service
metadata: 
  name: myservice
spec:
  selector:
    app: webs 
    env: dev
  ports:
    - name: webport
      protocol: TCP
      port: 8000
      targetPort: 80
  type: ClusterIP
