apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: pysureset
spec:
  revisionHistoryLimit: 4
  replicas: 20
  selector:
    matchLabels:
      app: nginx
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1 
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        ports:
        - containerPort: 80